import {
  FarmerProfile,
  ProcurementCentre,
  Appointment,
  ProcurementRecord,
  PaymentRecord,
  CentreAlert,
  ModelComparisonMetric,
  HourlyForecast
} from '../types';

export const INITIAL_FARMERS: FarmerProfile[] = [
  {
    id: 'f-1',
    name: 'Ramesh Gowda',
    phone: '98451 23450',
    farmerId: 'KA-FARM-882190',
    village: 'Devenahalli Rural',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    language: 'en'
  },
  {
    id: 'f-2',
    name: 'Manjunath K',
    phone: '94481 99231',
    farmerId: 'KA-FARM-771029',
    village: 'Nelamangala Hobli',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-3',
    name: 'Chennappa Reddi',
    phone: '99002 44102',
    farmerId: 'KA-FARM-660144',
    village: 'Doddaballapur',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-4',
    name: 'Lakshmi Devi',
    phone: '97312 88401',
    farmerId: 'KA-FARM-993812',
    village: 'Hoskote Taluk',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-5',
    name: 'Suresh Patil',
    phone: '94801 33490',
    farmerId: 'KA-FARM-449102',
    village: 'Maddur West',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-6',
    name: 'Basavaraj H',
    phone: '98440 11984',
    farmerId: 'KA-FARM-339182',
    village: 'Srirangapatna',
    district: 'Mandya',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-7',
    name: 'Shivanna M',
    phone: '99801 77239',
    farmerId: 'KA-FARM-552190',
    village: 'Nanjangud Rural',
    district: 'Mysuru',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-8',
    name: 'Anusuya Bai',
    phone: '96112 00481',
    farmerId: 'KA-FARM-119284',
    village: 'Tiptur North',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-9',
    name: 'Venkatesh Murthy',
    phone: '97400 66291',
    farmerId: 'KA-FARM-228491',
    village: 'Channarayapatna',
    district: 'Hassan',
    state: 'Karnataka',
    language: 'kn'
  },
  {
    id: 'f-10',
    name: 'Devendrappa N',
    phone: '98803 44921',
    farmerId: 'KA-FARM-839201',
    village: 'Kunigal East',
    district: 'Tumakuru',
    state: 'Karnataka',
    language: 'kn'
  }
];

export const INITIAL_CENTRES: ProcurementCentre[] = [
  {
    id: 'c-1',
    name: 'Bengaluru Agricultural Procurement Centre',
    district: 'Bengaluru Urban / Rural',
    address: 'APMC Yard Gate 2, Yeshwanthpur Industrial Suburb',
    distanceKm: 4.2,
    expectedLoad: 'Medium',
    activeCounters: 4,
    totalCounters: 5,
    currentQueueLength: 14,
    avgWaitMinutes: 35,
    avgProcessingMinutes: 7,
    todayCompleted: 86,
    capacityUtilizationPercent: 78,
    coordinates: { lat: 13.0285, lng: 77.5456, x: 58, y: 44 },
    operatingHours: '08:30 AM - 05:30 PM',
    contactNumber: '+91 80 2341 8800'
  },
  {
    id: 'c-2',
    name: 'Mandya District Grain Mandi Hub',
    district: 'Mandya',
    address: 'Kalyani Lake Road, Near State Warehousing Corp',
    distanceKm: 18.5,
    expectedLoad: 'High',
    activeCounters: 3,
    totalCounters: 4,
    currentQueueLength: 26,
    avgWaitMinutes: 55,
    avgProcessingMinutes: 8,
    todayCompleted: 62,
    capacityUtilizationPercent: 92,
    coordinates: { lat: 12.5218, lng: 76.8951, x: 40, y: 68 },
    operatingHours: '08:00 AM - 05:00 PM',
    contactNumber: '+91 8232 221040'
  },
  {
    id: 'c-3',
    name: 'Mysuru South Commodity Procurement Centre',
    district: 'Mysuru',
    address: 'Bandi Palya APMC Complex, Mysuru - Ooty Road',
    distanceKm: 32.0,
    expectedLoad: 'Low',
    activeCounters: 5,
    totalCounters: 6,
    currentQueueLength: 8,
    avgWaitMinutes: 18,
    avgProcessingMinutes: 6,
    todayCompleted: 104,
    capacityUtilizationPercent: 52,
    coordinates: { lat: 12.2812, lng: 76.6781, x: 30, y: 82 },
    operatingHours: '08:30 AM - 06:00 PM',
    contactNumber: '+91 821 2490120'
  },
  {
    id: 'c-4',
    name: 'Tumakuru Sub-Market Yard',
    district: 'Tumakuru',
    address: 'B.H. Road, Industrial Area Phase 1',
    distanceKm: 26.4,
    expectedLoad: 'Medium',
    activeCounters: 3,
    totalCounters: 4,
    currentQueueLength: 16,
    avgWaitMinutes: 38,
    avgProcessingMinutes: 7.5,
    todayCompleted: 71,
    capacityUtilizationPercent: 74,
    coordinates: { lat: 13.3409, lng: 77.1006, x: 50, y: 28 },
    operatingHours: '09:00 AM - 05:30 PM',
    contactNumber: '+91 816 2271890'
  },
  {
    id: 'c-5',
    name: 'Hassan Agro-Depot Centre',
    district: 'Hassan',
    address: 'KRS Industrial Ring Road, By-pass Junction',
    distanceKm: 44.0,
    expectedLoad: 'Low',
    activeCounters: 4,
    totalCounters: 4,
    currentQueueLength: 6,
    avgWaitMinutes: 15,
    avgProcessingMinutes: 6.5,
    todayCompleted: 58,
    capacityUtilizationPercent: 44,
    coordinates: { lat: 13.0033, lng: 76.1004, x: 22, y: 52 },
    operatingHours: '09:00 AM - 05:00 PM',
    contactNumber: '+91 8172 268410'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-110',
    tokenNumber: 'A-110',
    farmerId: 'f-3',
    farmerName: 'Chennappa Reddi',
    farmerPhone: '99002 44102',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 650,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '09:00 AM - 09:30 AM',
    status: 'COMPLETED',
    createdAt: '2026-09-25T14:10:00Z',
    qrCodeData: 'KQ:c-1:A-110:f-3'
  },
  {
    id: 'apt-111',
    tokenNumber: 'A-111',
    farmerId: 'f-4',
    farmerName: 'Lakshmi Devi',
    farmerPhone: '97312 88401',
    crop: 'Ragi (Finger Millet)',
    bookedQuantityKg: 400,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '09:30 AM - 10:00 AM',
    status: 'COMPLETED',
    createdAt: '2026-09-25T14:40:00Z',
    qrCodeData: 'KQ:c-1:A-111:f-4'
  },
  {
    id: 'apt-112',
    tokenNumber: 'A-112',
    farmerId: 'f-2',
    farmerName: 'Manjunath K',
    farmerPhone: '94481 99231',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 800,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'NOW_SERVING',
    createdAt: '2026-09-25T15:20:00Z',
    qrCodeData: 'KQ:c-1:A-112:f-2'
  },
  {
    id: 'apt-113',
    tokenNumber: 'A-113',
    farmerId: 'f-5',
    farmerName: 'Suresh Patil',
    farmerPhone: '94801 33490',
    crop: 'Wheat',
    bookedQuantityKg: 500,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:00 AM - 10:30 AM',
    status: 'WAITING',
    createdAt: '2026-09-25T15:35:00Z',
    qrCodeData: 'KQ:c-1:A-113:f-5'
  },
  {
    id: 'apt-114',
    tokenNumber: 'A-114',
    farmerId: 'f-6',
    farmerName: 'Basavaraj H',
    farmerPhone: '98440 11984',
    crop: 'Maize',
    bookedQuantityKg: 1200,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    status: 'WAITING',
    createdAt: '2026-09-25T16:00:00Z',
    qrCodeData: 'KQ:c-1:A-114:f-6'
  },
  {
    id: 'apt-115',
    tokenNumber: 'A-115',
    farmerId: 'f-7',
    farmerName: 'Shivanna M',
    farmerPhone: '99801 77239',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 450,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    status: 'WAITING',
    createdAt: '2026-09-25T16:15:00Z',
    qrCodeData: 'KQ:c-1:A-115:f-7'
  },
  {
    id: 'apt-116',
    tokenNumber: 'A-116',
    farmerId: 'f-8',
    farmerName: 'Anusuya Bai',
    farmerPhone: '96112 00481',
    crop: 'Ragi (Finger Millet)',
    bookedQuantityKg: 600,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    status: 'WAITING',
    createdAt: '2026-09-25T16:30:00Z',
    qrCodeData: 'KQ:c-1:A-116:f-8'
  },
  {
    id: 'apt-117',
    tokenNumber: 'A-117',
    farmerId: 'f-9',
    farmerName: 'Venkatesh Murthy',
    farmerPhone: '97400 66291',
    crop: 'Maize',
    bookedQuantityKg: 950,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    status: 'WAITING',
    createdAt: '2026-09-25T16:45:00Z',
    qrCodeData: 'KQ:c-1:A-117:f-9'
  },
  {
    id: 'apt-118',
    tokenNumber: 'A-118',
    farmerId: 'f-10',
    farmerName: 'Devendrappa N',
    farmerPhone: '98803 44921',
    crop: 'Wheat',
    bookedQuantityKg: 520,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:00 AM - 11:30 AM',
    status: 'WAITING',
    createdAt: '2026-09-25T17:00:00Z',
    qrCodeData: 'KQ:c-1:A-118:f-10'
  },
  {
    id: 'apt-119',
    tokenNumber: 'A-119',
    farmerId: 'f-1',
    farmerName: 'Ramesh Gowda',
    farmerPhone: '98451 23450',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 500,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:15:00Z',
    qrCodeData: 'KQ:c-1:A-124:f-1'
  },
  {
    id: 'apt-120',
    tokenNumber: 'A-120',
    farmerId: 'f-3',
    farmerName: 'Chennappa Reddi',
    farmerPhone: '99002 44102',
    crop: 'Wheat',
    bookedQuantityKg: 700,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:00 AM - 11:30 AM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:20:00Z',
    qrCodeData: 'KQ:c-1:A-120:f-3'
  },
  {
    id: 'apt-121',
    tokenNumber: 'A-121',
    farmerId: 'f-4',
    farmerName: 'Lakshmi Devi',
    farmerPhone: '97312 88401',
    crop: 'Ragi (Finger Millet)',
    bookedQuantityKg: 350,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:00 AM - 11:30 AM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:25:00Z',
    qrCodeData: 'KQ:c-1:A-121:f-4'
  },
  {
    id: 'apt-122',
    tokenNumber: 'A-122',
    farmerId: 'f-5',
    farmerName: 'Suresh Patil',
    farmerPhone: '94801 33490',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 600,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:00 AM - 11:30 AM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:30:00Z',
    qrCodeData: 'KQ:c-1:A-122:f-5'
  },
  {
    id: 'apt-123',
    tokenNumber: 'A-123',
    farmerId: 'f-6',
    farmerName: 'Basavaraj H',
    farmerPhone: '98440 11984',
    crop: 'Maize',
    bookedQuantityKg: 850,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:30 AM - 12:00 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:35:00Z',
    qrCodeData: 'KQ:c-1:A-123:f-6'
  },
  // The spotlight farmer appointment (A-124)
  {
    id: 'apt-124',
    tokenNumber: 'A-124',
    farmerId: 'f-1',
    farmerName: 'Ramesh Gowda',
    farmerPhone: '98451 23450',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 500,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '10:30 AM - 11:00 AM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:40:00Z',
    qrCodeData: 'KQ:c-1:A-124:f-1'
  },
  {
    id: 'apt-125',
    tokenNumber: 'A-125',
    farmerId: 'f-7',
    farmerName: 'Shivanna M',
    farmerPhone: '99801 77239',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 520,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:30 AM - 12:00 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:45:00Z',
    qrCodeData: 'KQ:c-1:A-125:f-7'
  },
  {
    id: 'apt-126',
    tokenNumber: 'A-126',
    farmerId: 'f-8',
    farmerName: 'Anusuya Bai',
    farmerPhone: '96112 00481',
    crop: 'Ragi (Finger Millet)',
    bookedQuantityKg: 400,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '11:30 AM - 12:00 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:50:00Z',
    qrCodeData: 'KQ:c-1:A-126:f-8'
  },
  {
    id: 'apt-127',
    tokenNumber: 'A-127',
    farmerId: 'f-9',
    farmerName: 'Venkatesh Murthy',
    farmerPhone: '97400 66291',
    crop: 'Wheat',
    bookedQuantityKg: 640,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '12:00 PM - 12:30 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T07:55:00Z',
    qrCodeData: 'KQ:c-1:A-127:f-9'
  },
  {
    id: 'apt-128',
    tokenNumber: 'A-128',
    farmerId: 'f-10',
    farmerName: 'Devendrappa N',
    farmerPhone: '98803 44921',
    crop: 'Maize',
    bookedQuantityKg: 800,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '12:00 PM - 12:30 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T08:00:00Z',
    qrCodeData: 'KQ:c-1:A-128:f-10'
  },
  {
    id: 'apt-129',
    tokenNumber: 'A-129',
    farmerId: 'f-2',
    farmerName: 'Manjunath K',
    farmerPhone: '94481 99231',
    crop: 'Wheat',
    bookedQuantityKg: 500,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '12:00 PM - 12:30 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T08:05:00Z',
    qrCodeData: 'KQ:c-1:A-129:f-2'
  },
  {
    id: 'apt-130',
    tokenNumber: 'A-130',
    farmerId: 'f-3',
    farmerName: 'Chennappa Reddi',
    farmerPhone: '99002 44102',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 750,
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    date: '26 Sep 2026',
    timeSlot: '12:30 PM - 01:00 PM',
    status: 'WAITING',
    createdAt: '2026-09-26T08:10:00Z',
    qrCodeData: 'KQ:c-1:A-130:f-3'
  }
];

export const INITIAL_PROCUREMENT_RECORDS: ProcurementRecord[] = [
  {
    id: 'pr-101',
    appointmentId: 'apt-110',
    tokenNumber: 'A-110',
    farmerId: 'f-3',
    farmerName: 'Chennappa Reddi',
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 650,
    actualQuantityKg: 642,
    qualityStatus: 'Grade A (FAQ Standard)',
    moisturePercent: 13.8,
    mspRatePerQuintal: 2320,
    procurementAmount: 148944,
    completedAt: '2026-09-26T09:22:00Z',
    operatorId: 'op-01',
    operatorName: 'Anil Kumar (Operator #4)',
    weighbridgeSlipNo: 'WB-2026-0926-041'
  },
  {
    id: 'pr-102',
    appointmentId: 'apt-111',
    tokenNumber: 'A-111',
    farmerId: 'f-4',
    farmerName: 'Lakshmi Devi',
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    crop: 'Ragi (Finger Millet)',
    bookedQuantityKg: 400,
    actualQuantityKg: 395,
    qualityStatus: 'Grade A (FAQ Standard)',
    moisturePercent: 12.1,
    mspRatePerQuintal: 4290,
    procurementAmount: 169455,
    completedAt: '2026-09-26T09:48:00Z',
    operatorId: 'op-01',
    operatorName: 'Anil Kumar (Operator #4)',
    weighbridgeSlipNo: 'WB-2026-0926-042'
  },
  // Ramesh Gowda's previous historical records (from F11/F12/F13 prompts)
  {
    id: 'pr-099',
    appointmentId: 'apt-099',
    tokenNumber: 'A-089',
    farmerId: 'f-1',
    farmerName: 'Ramesh Gowda',
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 500,
    actualQuantityKg: 492,
    qualityStatus: 'Grade A (FAQ Standard)',
    moisturePercent: 13.4,
    mspRatePerQuintal: 2320,
    procurementAmount: 114144, // ₹42,500 can be displayed or 42,500 as in prompt
    completedAt: '2026-09-23T11:45:00Z',
    operatorId: 'op-02',
    operatorName: 'Harish R (Operator #2)',
    weighbridgeSlipNo: 'WB-2026-0923-018'
  },
  {
    id: 'pr-088',
    appointmentId: 'apt-088',
    tokenNumber: 'A-042',
    farmerId: 'f-1',
    farmerName: 'Ramesh Gowda',
    centreId: 'c-1',
    centreName: 'Bengaluru Agricultural Procurement Centre',
    crop: 'Rice (Paddy)',
    bookedQuantityKg: 480,
    actualQuantityKg: 480,
    qualityStatus: 'Grade A (FAQ Standard)',
    moisturePercent: 13.0,
    mspRatePerQuintal: 2280,
    procurementAmount: 41200, // Matching prompt: 18 Sep, 480kg, ₹41,200 Paid
    completedAt: '2026-09-18T10:15:00Z',
    operatorId: 'op-01',
    operatorName: 'Anil Kumar (Operator #4)',
    weighbridgeSlipNo: 'WB-2026-0918-009'
  }
];

export const INITIAL_PAYMENT_RECORDS: PaymentRecord[] = [
  {
    id: 'pay-001',
    procurementRecordId: 'pr-099',
    tokenNumber: 'A-089',
    farmerId: 'f-1',
    farmerName: 'Ramesh Gowda',
    bankAccountMasked: 'SBIN••••••4821',
    ifscCode: 'SBIN0040182',
    amount: 42500,
    status: 'BANK_PROCESSING',
    initiatedAt: '2026-09-23T12:00:00Z',
    referenceId: 'KQ20260923001'
  },
  {
    id: 'pay-002',
    procurementRecordId: 'pr-088',
    tokenNumber: 'A-042',
    farmerId: 'f-1',
    farmerName: 'Ramesh Gowda',
    bankAccountMasked: 'SBIN••••••4821',
    ifscCode: 'SBIN0040182',
    amount: 41200,
    status: 'COMPLETED',
    initiatedAt: '2026-09-18T11:00:00Z',
    completedAt: '2026-09-18T15:30:00Z',
    referenceId: 'KQ20260918077'
  },
  {
    id: 'pay-003',
    procurementRecordId: 'pr-101',
    tokenNumber: 'A-110',
    farmerId: 'f-3',
    farmerName: 'Chennappa Reddi',
    bankAccountMasked: 'CNRB••••••9012',
    ifscCode: 'CNRB0001092',
    amount: 148944,
    status: 'BANK_PROCESSING',
    initiatedAt: '2026-09-26T09:30:00Z',
    referenceId: 'KQ20260926012'
  },
  {
    id: 'pay-004',
    procurementRecordId: 'pr-102',
    tokenNumber: 'A-111',
    farmerId: 'f-4',
    farmerName: 'Lakshmi Devi',
    bankAccountMasked: 'KARB••••••2231',
    ifscCode: 'KARB0000412',
    amount: 169455,
    status: 'INITIATED',
    initiatedAt: '2026-09-26T09:55:00Z',
    referenceId: 'KQ20260926019'
  }
];

export const INITIAL_ALERTS: CentreAlert[] = [
  {
    id: 'alt-1',
    centreId: 'c-1',
    centreName: 'Bengaluru Procurement Centre',
    type: 'HIGH_CONGESTION',
    title: 'High Congestion Warning',
    message: 'Bengaluru Centre may exceed peak processing capacity between 12:00 PM – 02:00 PM due to incoming slot clustering.',
    severity: 'warning',
    timestamp: '25 min ago',
    actionRequired: 'Shift next available slots to 02:30 PM window and notify incoming farmers.'
  },
  {
    id: 'alt-2',
    centreId: 'c-2',
    centreName: 'Mandya Grain Mandi Hub',
    type: 'CAPACITY_ALERT',
    title: 'Counter Availability Alert',
    message: 'Only 3 of 4 active counters available. Counter #2 moisture analyzer undergoing recalibration.',
    severity: 'critical',
    timestamp: '40 min ago',
    actionRequired: 'Deploy backup handheld grain analyzer or throttle token emission rate.'
  },
  {
    id: 'alt-3',
    centreId: 'c-1',
    centreName: 'State-wide Clearing Portal',
    type: 'PAYMENT_ALERT',
    title: 'DBT Batch Payment Clearance',
    message: '24 procurement payments are pending PFMS gateway token confirmation across Bengaluru & Mandya divisions.',
    severity: 'warning',
    timestamp: '1 hour ago',
    actionRequired: 'Trigger batch resync with PFMS API endpoint.'
  },
  {
    id: 'alt-4',
    centreId: 'c-3',
    centreName: 'Mysuru South Mandi',
    type: 'WEATHER_ADVISORY',
    title: 'Post-noon Rain Forecast',
    message: '30% chance of showers after 03:00 PM. Covered unloading bay priority activated.',
    severity: 'low',
    timestamp: '2 hours ago',
    actionRequired: 'Direct tractor arrivals to covered shed bays 1-4.'
  }
];

export const MODEL_METRICS: ModelComparisonMetric[] = [
  {
    modelName: 'Gradient Boosting Regressor (GBR)',
    mae: 4.2, // ±4.2 minutes mean error
    rmse: 5.8,
    r2Score: 0.912,
    latencyMs: 14,
    isChampion: true
  },
  {
    modelName: 'Random Forest Regressor (RF)',
    mae: 6.5,
    rmse: 8.4,
    r2Score: 0.854,
    latencyMs: 28,
    isChampion: false
  },
  {
    modelName: 'Multiple Linear Regression (OLS)',
    mae: 11.8,
    rmse: 15.2,
    r2Score: 0.681,
    latencyMs: 4,
    isChampion: false
  }
];

export const HOURLY_CONGESTION_FORECAST: HourlyForecast[] = [
  { hourLabel: '09:00 AM', expectedFarmers: 18, processingCapacity: 28, predictedLoad: 'Low', avgPredictedWaitMinutes: 16 },
  { hourLabel: '10:00 AM', expectedFarmers: 32, processingCapacity: 28, predictedLoad: 'Medium', avgPredictedWaitMinutes: 28 },
  { hourLabel: '11:00 AM', expectedFarmers: 42, processingCapacity: 28, predictedLoad: 'Medium', avgPredictedWaitMinutes: 38 },
  { hourLabel: '12:00 PM', expectedFarmers: 58, processingCapacity: 28, predictedLoad: 'High', avgPredictedWaitMinutes: 58 },
  { hourLabel: '01:00 PM', expectedFarmers: 64, processingCapacity: 24, predictedLoad: 'High', avgPredictedWaitMinutes: 62 },
  { hourLabel: '02:00 PM', expectedFarmers: 48, processingCapacity: 28, predictedLoad: 'High', avgPredictedWaitMinutes: 46 },
  { hourLabel: '03:00 PM', expectedFarmers: 34, processingCapacity: 28, predictedLoad: 'Medium', avgPredictedWaitMinutes: 32 },
  { hourLabel: '04:00 PM', expectedFarmers: 22, processingCapacity: 28, predictedLoad: 'Low', avgPredictedWaitMinutes: 18 },
  { hourLabel: '05:00 PM', expectedFarmers: 12, processingCapacity: 20, predictedLoad: 'Low', avgPredictedWaitMinutes: 12 }
];

export const HISTORICAL_DEMAND_7DAYS = [
  { dateLabel: '20 Sep', historical: 1940, capacity: 2200 },
  { dateLabel: '21 Sep', historical: 2110, capacity: 2200 },
  { dateLabel: '22 Sep', historical: 2280, capacity: 2200 },
  { dateLabel: '23 Sep', historical: 2450, capacity: 2200 },
  { dateLabel: '24 Sep', historical: 2390, capacity: 2200 },
  { dateLabel: '25 Sep', historical: 2410, capacity: 2200 },
  { dateLabel: '26 Sep (Today)', historical: 2480, capacity: 2200 },
  // Projected next 3 days
  { dateLabel: '27 Sep (Forecast)', forecast: 2560, capacity: 2400 },
  { dateLabel: '28 Sep (Forecast)', forecast: 2320, capacity: 2400 },
  { dateLabel: '29 Sep (Forecast)', forecast: 1980, capacity: 2400 }
];

export const MSP_RATES: Record<string, number> = {
  'Rice (Paddy)': 2320, // Rs per quintal (100 kg)
  'Wheat': 2425,
  'Maize': 2225,
  'Ragi (Finger Millet)': 4290,
  'Toor Dal': 7550,
  'Other': 2500
};

export const INITIAL_NOTIFICATIONS: import('../types').AppNotification[] = [
  // --- FARMER CHANNEL (e.g. Farmer Ravi Kumar - Token A-124) ---
  {
    id: 'notif-farm-1',
    channel: 'farmer',
    recipient: 'Farmer Ravi Kumar (Token A-124)',
    registeredNumber: 'KA-FARM-882190',
    title: 'Your Turn is Approaching! (Token A-124)',
    message: 'Token A-124: You are 4 farmers away in queue. Please move your tractor toward Weighbridge Bay #2 within 15 minutes.',
    category: 'queue',
    timestamp: '2 min ago',
    read: false,
    urgent: true,
    actionScreen: 'live_queue',
    actionLabel: 'Track Live Queue',
    metadata: { tokenNumber: 'A-124', bayId: 'Bay #2' }
  },
  {
    id: 'notif-farm-2',
    channel: 'farmer',
    recipient: 'Farmer Ravi Kumar',
    registeredNumber: 'KA-FARM-882190',
    title: 'Weighbridge Digital Certificate Issued',
    message: 'Net certified produce of 492 kg Grade A Rice (Paddy) confirmed. Weighbridge slip WB-2026-0926-048 generated.',
    category: 'system',
    timestamp: '18 min ago',
    read: false,
    urgent: false,
    actionScreen: 'procurement_status',
    actionLabel: 'View Weighment Slip',
    metadata: { weightKg: 492 }
  },
  {
    id: 'notif-farm-3',
    channel: 'farmer',
    recipient: 'Farmer Ravi Kumar',
    registeredNumber: 'KA-FARM-882190',
    title: 'DBT Treasury Payment Credited (₹42,500)',
    message: 'Direct Benefit Transfer voucher of ₹42,500 credited to State Bank of India A/c ••••4821 via PFMS clearing.',
    category: 'payment',
    timestamp: '45 min ago',
    read: false,
    urgent: false,
    actionScreen: 'payment_status',
    actionLabel: 'View Payment Status',
    metadata: { amount: 42500 }
  },
  {
    id: 'notif-farm-4',
    channel: 'farmer',
    recipient: 'Farmer Ravi Kumar',
    registeredNumber: 'KA-FARM-882190',
    title: 'Official APMC Mandi MSP Advisory',
    message: 'Government MSP notified: Common Paddy at ₹2,320/qtl, Ragi at ₹4,290/qtl. Moisture FAQ threshold capped at 14.0%.',
    category: 'mandi',
    timestamp: '2 hours ago',
    read: true,
    urgent: false
  },

  // --- WEIGHBRIDGE BAY CHANNEL (e.g. Weighbridge Bay #2 Operator) ---
  {
    id: 'notif-bay-1',
    channel: 'bay',
    recipient: 'Weighbridge Bay #2 (Operator)',
    registeredNumber: 'OP-KAR-2041',
    title: 'Incoming Tractor Arrival at Bay #2',
    message: 'Vehicle KA-04-E-8821 with Token A-124 (Farmer Ravi Kumar) has checked in at North Gate. Tare scale standby.',
    category: 'bay_operation',
    timestamp: '4 min ago',
    read: false,
    urgent: true,
    actionScreen: 'operator_bay',
    actionLabel: 'Open Weigh Scale',
    metadata: { tokenNumber: 'A-124', vehicleNumber: 'KA-04-E-8821', bayId: 'Bay #2' }
  },
  {
    id: 'notif-bay-2',
    channel: 'bay',
    recipient: 'Weighbridge Bay #2 (Operator)',
    registeredNumber: 'OP-KAR-2041',
    title: 'Gross Tare Weight Capture Completed',
    message: 'Gross weight 3,240 kg captured for Token A-122. Unloading dispatched to Covered Shed Bay 4.',
    category: 'bay_operation',
    timestamp: '22 min ago',
    read: false,
    urgent: false,
    metadata: { weightKg: 3240, bayId: 'Bay #2' }
  },
  {
    id: 'notif-bay-3',
    channel: 'bay',
    recipient: 'Weighbridge Bay #2 (Operator)',
    registeredNumber: 'OP-KAR-2041',
    title: 'Moisture Analyzer Auto-Calibration Passed',
    message: 'Bay #2 digital grain analyzer self-check completed. Variance index 0.04% (within permissible ISI tolerance).',
    category: 'system',
    timestamp: '1 hour ago',
    read: true,
    urgent: false
  },
  {
    id: 'notif-bay-4',
    channel: 'bay',
    recipient: 'Weighbridge Bay #1 & #2',
    registeredNumber: 'OP-KAR-2041',
    title: 'Yard Logistics: Multi-axle Ingress Advisory',
    message: 'High heavy-vehicle ingress detected on Ring Road access ramp. Maintain 4-minute vehicle separation.',
    category: 'system',
    timestamp: '3 hours ago',
    read: true,
    urgent: false
  },

  // --- SSO / DIRECTORATE CHANNEL (e.g. Directorate Mandi Command Admin) ---
  {
    id: 'notif-sso-1',
    channel: 'sso',
    recipient: 'Directorate SSO Admin (Command Center)',
    registeredNumber: 'SSO-DIR-KA01',
    title: 'Daily Procurement Quota: 84% Capacity Reached',
    message: 'Bengaluru APMC procurement division has registered 2,480 MT today (84% of daily target). Buffer allocation active.',
    category: 'sso_governance',
    timestamp: '10 min ago',
    read: false,
    urgent: true,
    actionScreen: 'admin_command',
    actionLabel: 'View Mandi Analytics'
  },
  {
    id: 'notif-sso-2',
    channel: 'sso',
    recipient: 'Directorate SSO Admin (Command Center)',
    registeredNumber: 'SSO-DIR-KA01',
    title: 'PFMS DBT Treasury Clearance: 24 Vouchers',
    message: 'Batch #PFMS-KA-9921 for ₹1.84 Cr successfully approved and transmitted to RBI e-Kuber clearing portal.',
    category: 'payment',
    timestamp: '35 min ago',
    read: false,
    urgent: false,
    actionScreen: 'admin_command',
    actionLabel: 'View Settlement Log'
  },
  {
    id: 'notif-sso-3',
    channel: 'sso',
    recipient: 'Directorate SSO Admin (Command Center)',
    registeredNumber: 'SSO-DIR-KA01',
    title: 'Quality Anomaly Flagged at Mandya Hub',
    message: 'Counter #2 at Mandya Hub recorded 16.8% moisture on Batch #M-104. Automated re-drying flag dispatched.',
    category: 'sso_governance',
    timestamp: '1 hour ago',
    read: true,
    urgent: false
  },
  {
    id: 'notif-sso-4',
    channel: 'sso',
    recipient: 'Directorate SSO Admin (Command Center)',
    registeredNumber: 'SSO-DIR-KA01',
    title: 'e-NAM National Portal Daily Price Ticker Synced',
    message: 'Karnataka APMC price feeds successfully synchronized with the central e-NAM unified market gateway.',
    category: 'mandi',
    timestamp: '4 hours ago',
    read: true,
    urgent: false
  }
];
